resources:
- name: my-pipelines
  type: concourse-pipeline
  source:
    teams:
    - name: main
- name: repo
  type: git
  source:
    uri: git@github.com:ikhripunov/demo
    branch: master
- name: every-30s
  type: time
  source: {interval: 30s}

jobs:
- name: ouroboros
  plan:
  - get: every-30s
    trigger: true
  - get: repo
  - task: bite-the-tail
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: /bin/sh
        args: ["-c", "echo $(ls ~/repo)"]

